// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientService.proto

package org.minbox.framework.message.pipe.core.grpc.proto;

public interface ClientResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.minbox.framework.message.pipe.core.grpc.proto.ClientResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string body = 1;</code>
   * @return The body.
   */
  String getBody();
  /**
   * <code>string body = 1;</code>
   * @return The bytes for body.
   */
  com.google.protobuf.ByteString
      getBodyBytes();
}
