// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientService.proto

package org.minbox.framework.message.pipe.core.grpc.proto;

public final class ClientServiceProto {
  private ClientServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_minbox_framework_message_pipe_core_grpc_ClientRegisterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_minbox_framework_message_pipe_core_grpc_ClientRegisterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_minbox_framework_message_pipe_core_grpc_ClientHeartBeatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_minbox_framework_message_pipe_core_grpc_ClientHeartBeatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_minbox_framework_message_pipe_core_grpc_ClientResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_minbox_framework_message_pipe_core_grpc_ClientResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023ClientService.proto\022+org.minbox.framew" +
      "ork.message.pipe.core.grpc\"O\n\025ClientRegi" +
      "sterRequest\022\027\n\017messagePipeName\030\001 \001(\t\022\017\n\007" +
      "address\030\002 \001(\t\022\014\n\004port\030\003 \001(\005\"7\n\026ClientHea" +
      "rtBeatRequest\022\017\n\007address\030\001 \001(\t\022\014\n\004port\030\002" +
      " \001(\005\"\036\n\016ClientResponse\022\014\n\004body\030\001 \001(\t2\255\002\n" +
      "\rClientService\022\213\001\n\010register\022B.org.minbox" +
      ".framework.message.pipe.core.grpc.Client" +
      "RegisterRequest\032;.org.minbox.framework.m" +
      "essage.pipe.core.grpc.ClientResponse\022\215\001\n" +
      "\theartbeat\022C.org.minbox.framework.messag" +
      "e.pipe.core.grpc.ClientHeartBeatRequest\032" +
      ";.org.minbox.framework.message.pipe.core" +
      ".grpc.ClientResponseB\026B\022ClientServicePro" +
      "toP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_minbox_framework_message_pipe_core_grpc_ClientRegisterRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_minbox_framework_message_pipe_core_grpc_ClientRegisterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_minbox_framework_message_pipe_core_grpc_ClientRegisterRequest_descriptor,
        new String[] { "MessagePipeName", "Address", "Port", });
    internal_static_org_minbox_framework_message_pipe_core_grpc_ClientHeartBeatRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_minbox_framework_message_pipe_core_grpc_ClientHeartBeatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_minbox_framework_message_pipe_core_grpc_ClientHeartBeatRequest_descriptor,
        new String[] { "Address", "Port", });
    internal_static_org_minbox_framework_message_pipe_core_grpc_ClientResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_minbox_framework_message_pipe_core_grpc_ClientResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_minbox_framework_message_pipe_core_grpc_ClientResponse_descriptor,
        new String[] { "Body", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
