// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientService.proto

package org.minbox.framework.message.pipe.core.grpc.proto;

public interface ClientRegisterRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.minbox.framework.message.pipe.core.grpc.proto.ClientRegisterRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string messagePipeName = 1;</code>
   */
  String getMessagePipeName();
  /**
   * <code>string messagePipeName = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessagePipeNameBytes();

  /**
   * <code>string address = 2;</code>
   */
  String getAddress();
  /**
   * <code>string address = 2;</code>
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>int32 port = 3;</code>
   */
  int getPort();
}
