// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageService.proto

package org.minbox.framework.message.pipe.core.grpc.proto;

public interface MessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.minbox.framework.message.pipe.core.grpc.MessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string body = 1;</code>
   */
  String getBody();
  /**
   * <code>string body = 1;</code>
   */
  com.google.protobuf.ByteString
      getBodyBytes();
}
